### ISSUE TITLE
Setup auto plugin deploy

### ISSUE THREAD

**Issue by mauryaratan** [Codestag/stagtools#40]
Hey @lushkant,

Can you please set up auto deploy for this repo? I've it set on https://github.com/mauryaratan/embed-sendy if you need a quick start.

Ping me if you have any questions.

**Comment by lushkant** [comment]
gotcha, will do!

**Comment by mauryaratan** [comment]
@lushkant would be good to get this done soon, so we still have StagTools update pending.

**Comment by lushkant** [comment]
@mauryaratan I've added the deploy action should this do it? 😃  let me know if I need to take care of something else.

**Comment by lushkant** [comment]
@mauryaratan please upload plugin assets in its respective dir.
