### ISSUE TITLE
Syntax Errors with v2.3.4

### ISSUE THREAD

**Issue by jonesch** [Codestag/stagtools#42]
With the latest version, 2.3.4, there are some syntax errors that are throwing 500 errors.

Here is the PHP Error Log for a site we manage:
```
[09-Oct-2020 15:07:31 UTC] PHP Parse error:  syntax error, unexpected ')' in /wp-content/plugins/stagtools/includes/widgets/widget-instagram.php on line 37
```

After taking a look, we see that on Line 36 and Line 49, there are commas after the second parameter being passed to `printf()`. Removing these commas fixed the syntax errors for us.

https://github.com/Codestag/stagtools/blob/master/includes/widgets/widget-instagram.php#L36
https://github.com/Codestag/stagtools/blob/master/includes/widgets/widget-instagram.php#L49

Thanks!

**Comment by lushkant** [comment]
@jonesch Thanks for the heads-up, we'll get this fixed. 🙂
