### ISSUE TITLE
Who to contact for security issues

### ISSUE THREAD

**Issue by psmoros** [codestag/stagtools#50]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@xplo1t-sec) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by lushkant** [comment]
Hi there @psmoros,

Thank you for the heads up, I have added the same as you requested and you can report anything unexpected at the address available in SECURITY.md file.

Once verifying the reported issue, we will get back to you asap!
Have a great day :)
